from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets/offline-preloader.js"

JSON_PATHS = [
    "assets/config.json",
    "content/pages.json",
    "content/toc.json",
    "content/i18n/sw-TZ/texts.json",
    "content/i18n/sw-TZ/audios.json",
    "content/i18n/sw-TZ/videos.json",
    "content/i18n/sw-TZ/glossary.json",
    "content/i18n/sw-TZ/timecode/timecode_output.json",
    "assets/interface_translations/sw-TZ/interface_translations.json",
]
TEXT_PATHS = [
    "assets/interface.html",
    "content/navigation/nav.html",
]

inline: dict[str, object] = {}
for relative in JSON_PATHS:
    path = ROOT / relative
    if path.exists():
        inline[f"./{relative}"] = json.loads(path.read_text())
for relative in TEXT_PATHS:
    path = ROOT / relative
    if path.exists():
        inline[f"./{relative}"] = path.read_text()

payload = json.dumps(inline, ensure_ascii=False, separators=(",", ":"))
script = f'''// offline-preloader.js — generated by scripts/generate_offline_preloader.py
(function () {{
  var INLINE = {payload};
  var CONFIG = INLINE["./assets/config.json"] || {{}};
  var AVAILABLE = (CONFIG.languages && CONFIG.languages.available) || [];
  var DEFAULT_LANGUAGE = (CONFIG.languages && CONFIG.languages.default) || AVAILABLE[0];

  // Discard a stale language saved by a different ADT bundle.
  try {{
    var saved = localStorage.getItem("currentLanguage");
    if (saved) {{
      try {{ saved = JSON.parse(saved); }} catch (_) {{}}
      if (AVAILABLE.indexOf(saved) === -1 && DEFAULT_LANGUAGE) {{
        localStorage.setItem("currentLanguage", JSON.stringify(DEFAULT_LANGUAGE));
      }}
    }}
  }} catch (_) {{}}

  var BASE_DIR = (function () {{
    var href = location.href.split("?")[0].split("#")[0];
    return href.slice(0, href.lastIndexOf("/") + 1);
  }})();

  function lookup(url) {{
    var clean = String(url).split("?")[0].split("#")[0];
    if (BASE_DIR && clean.indexOf(BASE_DIR) === 0) clean = clean.slice(BASE_DIR.length);
    if (clean.indexOf("./") === 0) clean = clean.slice(2);
    var withDot = "./" + clean;
    if (Object.prototype.hasOwnProperty.call(INLINE, withDot)) return withDot;
    if (Object.prototype.hasOwnProperty.call(INLINE, clean)) return clean;
    return null;
  }}

  var realFetch = window.fetch.bind(window);
  window.fetch = function (url, opts) {{
    var raw = (url && typeof url === "object" && typeof url.url === "string") ? url.url : url;
    var key = lookup(raw);
    if (key !== null) {{
      var data = INLINE[key];
      var isJson = key.slice(-5) === ".json";
      var body = isJson ? JSON.stringify(data) : data;
      var contentType = isJson ? "application/json" : "text/html; charset=utf-8";
      return Promise.resolve(new Response(body, {{status: 200, headers: {{"Content-Type": contentType}}}}));
    }}
    return realFetch(url, opts);
  }};
}})();
'''
OUTPUT.write_text(script)
print(f"Wrote {OUTPUT} with {len(inline)} embedded resources")
